# Generated by Django 4.0.2 on 2022-05-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_competitors_task_results_alter_task_event_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
