# Generated by Django 4.0.2 on 2022-05-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_title_task_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='competitor_name',
        ),
        migrations.AddField(
            model_name='task',
            name='division',
            field=models.CharField(default='', max_length=200),
        ),
    ]
