# Generated by Django 4.0.2 on 2022-05-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_task_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ring',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
