# Generated by Django 4.0.2 on 2022-05-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_task_ring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ring',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
